disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - todo
  - type_body_length

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call

type_name:
  max_length: 50
  excluded:
    - id

custom_rules:
  comment_space:
    name: "Space after comment slashes"
    regex: '(^ */{2,3}\w+)'
    message: "There should be a space after comment slashes."
    match_kinds:
      - comment
      - doccomment
    severity: warning
  todo_colon:
    name: "Colon after todo"
    regex: '(?i)todo[^:]'
    message: "There should be a colon after TODO."
    match_kinds:
      - comment
      - doccomment
    severity: warning
